# Generated by Django 5.1 on 2025-02-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('manage_project', 'Возможность управлять проектом')]},
        ),
    ]
